#ifndef STATIONTYPE_H
#define STATIONTYPE_H

enum class STATION_TYPE { NORMAL, VERTICAL, HORIZONTAL, DIAGONAL, B_DIAGONAL };

enum class NAMETAG_POSITION { TOP, BOTTOM, LEFT, RIGHT, TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT };

#endif // STATIONTYPE_H
